In [1]:
import numpy as np

In [3]:
l1=['BMW','BENZ','AUDI',5] 
ar1=np.array(l1)
print(ar1)
print(type(ar1))

['BMW' 'BENZ' 'AUDI' '5']
<class 'numpy.ndarray'>


In [4]:
print(ar1.shape)

(4,)


In [5]:
print(ar1[2])
print(ar1[0])

AUDI
BMW


In [6]:
print(ar1.reshape(1,4))
print(ar1.reshape(4,1))

[['BMW' 'BENZ' 'AUDI' '5']]
[['BMW']
 ['BENZ']
 ['AUDI']
 ['5']]


In [7]:
ar2=ar1.reshape(1,4)
ar3=ar1.reshape(4,1)
print(ar2.shape)
print(ar3.shape)

(1, 4)
(4, 1)


In [8]:
l2=['FERARI',2,1]
l3=[6,'ROLLS ROYCE',4]
l4=[9,8,'LAMBOGINI']
ar4=np.array([l2,l3,l4])
print(type(ar4))
print(ar4)
print(ar4.shape)

<class 'numpy.ndarray'>
[['FERARI' '2' '1']
 ['6' 'ROLLS ROYCE' '4']
 ['9' '8' 'LAMBOGINI']]
(3, 3)


In [9]:
print(ar4.reshape(1,9))
print(ar4.reshape(9,1))

[['FERARI' '2' '1' '6' 'ROLLS ROYCE' '4' '9' '8' 'LAMBOGINI']]
[['FERARI']
 ['2']
 ['1']
 ['6']
 ['ROLLS ROYCE']
 ['4']
 ['9']
 ['8']
 ['LAMBOGINI']]


In [10]:
ar2=ar1.reshape(1,4)
ar3=ar1.reshape(4,1)
print(ar2.shape)
print(ar3.shape)

(1, 4)
(4, 1)


In [11]:
l2=[3,2,1]
l3=[6,5,4]
l4=[9,8,7]
ar4=np.array([l2,l3,l4])
print(type(ar4))
print(ar4)
print(ar4.shape)

<class 'numpy.ndarray'>
[[3 2 1]
 [6 5 4]
 [9 8 7]]
(3, 3)


In [12]:
print(ar4.reshape(1,9))
print(ar4.reshape(9,1))

[[3 2 1 6 5 4 9 8 7]]
[[3]
 [2]
 [1]
 [6]
 [5]
 [4]
 [9]
 [8]
 [7]]


In [13]:
print(ar4)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [14]:
l5=[1,2,3,4,5]
l6=[7,8,9,0,1]
l7=[1,3,4,5,6]
l8=[7,7,2,3,4]
ar5=np.array([l5,l6,l7,l8])
print(ar5)

[[1 2 3 4 5]
 [7 8 9 0 1]
 [1 3 4 5 6]
 [7 7 2 3 4]]


In [15]:
print(ar5[:,:])

[[1 2 3 4 5]
 [7 8 9 0 1]
 [1 3 4 5 6]
 [7 7 2 3 4]]


In [16]:
print(ar5[2:,1:3])

[[3 4]
 [7 2]]


In [17]:
print(ar5[1:,1:])

[[8 9 0 1]
 [3 4 5 6]
 [7 2 3 4]]


In [18]:
print(ar5[1:3,:2])

[[7 8]
 [1 3]]
