In [3]:
import numpy as np

In [4]:
ar6=np.arange(1,10,2)
print(ar6)

[1 3 5 7 9]


In [5]:
ar7=np.linspace(1,20,10)
print(ar7)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [6]:
ar6*2

array([ 2,  6, 10, 14, 18])

In [7]:
ar6%2==0

array([False, False, False, False, False])

In [8]:
ar7[4:]=10
print(ar7)

[ 1.          3.11111111  5.22222222  7.33333333 10.         10.
 10.         10.         10.         10.        ]


In [9]:
ar7[4:8:2]=11
print(ar7)

[ 1.          3.11111111  5.22222222  7.33333333 11.         10.
 11.         10.         10.         10.        ]


In [10]:
ar8=[40,60,33,44,85,92]
print(ar8)

[40, 60, 33, 44, 85, 92]


In [11]:
print(np.random.rand(3,3))

[[0.58995906 0.61789471 0.33348159]
 [0.30251317 0.79852103 0.25275509]
 [0.96649493 0.73270811 0.9435534 ]]


In [12]:
print(np.random.randn(3,4))

[[-0.87569215  0.29652261 -0.5389843   2.26958652]
 [ 0.05840276  0.36883003 -0.54776936 -0.09673814]
 [-1.28037106  1.44766869  0.7669175   0.71570987]]
